/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as AtCircleDefs from "./defs.defs.js";

const $nsid = "net.asadaame5121.at-circle.banner";

export { $nsid };

/**
 * A banner image for a ring
 */
type Main = {
    $type: "net.asadaame5121.at-circle.banner";
    ring: AtCircleDefs.RingRef;
    banner: l.BlobRef;
    createdAt: l.DatetimeString;
};

export type { Main };

/**
 * A banner image for a ring
 */
const main = l.record<"tid", Main>(
    "tid",
    $nsid,
    l.object({
        ring: l.ref<AtCircleDefs.RingRef>((() => AtCircleDefs.ringRef) as any),
        banner: l.blob({
            accept: ["image/*"],
            maxSize: 1000000,
            allowLegacy: false,
        }),
        createdAt: l.string({ format: "datetime" }),
    }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
    $build = /*#__PURE__*/ main.build.bind(main),
    $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
    $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
    $matches = /*#__PURE__*/ main.matches.bind(main),
    $parse = /*#__PURE__*/ main.parse.bind(main),
    $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
