/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as AtCircleDefs from "./defs.defs.js";

const $nsid = "net.asadaame5121.at-circle.block";

export { $nsid };

/**
 * Block/Kick a member from the circle
 */
type Main = {
    $type: "net.asadaame5121.at-circle.block";

    /**
     * DID of the member to block
     */
    subject: l.DidString;
    ring: AtCircleDefs.RingRef;

    /**
     * Reason for blocking
     */
    reason?: string;
    createdAt: l.DatetimeString;
};

export type { Main };

/**
 * Block/Kick a member from the circle
 */
const main = l.record<"tid", Main>(
    "tid",
    $nsid,
    l.object({
        subject: l.string({ format: "did" }),
        ring: l.ref<AtCircleDefs.RingRef>((() => AtCircleDefs.ringRef) as any),
        reason: l.optional(l.string({ maxLength: 1000, maxGraphemes: 100 })),
        createdAt: l.string({ format: "datetime" }),
    }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
    $build = /*#__PURE__*/ main.build.bind(main),
    $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
    $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
    $matches = /*#__PURE__*/ main.matches.bind(main),
    $parse = /*#__PURE__*/ main.parse.bind(main),
    $safeParse = /*#__PURE__*/ main.safeParse.bind(main);
