/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'net.asadaame5121.at-circle.defs'

export { $nsid }

type RingRef = {
  $type?: 'net.asadaame5121.at-circle.defs#ringRef'

  /**
   * AT-URI of the Ring
   */
  uri: l.AtUriString

  /**
   * Optional CID for strong reference
   */
  cid?: l.CidString
}

export type { RingRef }

const ringRef = l.typedObject<RingRef>(
  $nsid,
  'ringRef',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
  }),
)

export { ringRef }
