/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtCircleDefs from './defs.defs.js'

const $nsid = 'net.asadaame5121.at-circle.member'

export { $nsid }

/**
 * Membership in an at-circle (Sidecar Record)
 */
type Main = {
  $type: 'net.asadaame5121.at-circle.member'
  ring: AtCircleDefs.RingRef

  /**
   * URL of the participant's site
   */
  url: l.UriString

  /**
   * Title of the participant's site
   */
  title: string

  /**
   * RSS feed URL
   */
  rss?: l.UriString
  createdAt: l.DatetimeString

  /**
   * Optional note
   */
  note?: string
}

export type { Main }

/**
 * Membership in an at-circle (Sidecar Record)
 */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    ring: l.ref<AtCircleDefs.RingRef>((() => AtCircleDefs.ringRef) as any),
    url: l.string({ format: 'uri' }),
    title: l.string({ maxLength: 1000, maxGraphemes: 100 }),
    rss: l.optional(l.string({ format: 'uri' })),
    createdAt: l.string({ format: 'datetime' }),
    note: l.optional(l.string({ maxLength: 3000, maxGraphemes: 300 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
