/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'net.asadaame5121.at-circle.ring'

export { $nsid }

/**
 * An at-circle group definition
 */
type Main = {
  $type: 'net.asadaame5121.at-circle.ring'

  /**
   * Name of the circle
   */
  title: string

  /**
   * Description of the circle
   */
  description?: string

  /**
   * Recruitment status
   */
  status: 'open' | 'closed' | l.UnknownString
  createdAt: l.DatetimeString
}

export type { Main }

/**
 * An at-circle group definition
 */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 1000, maxGraphemes: 100 }),
    description: l.optional(l.string({ maxLength: 10000, maxGraphemes: 1000 })),
    status: l.string(),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
